actions_search_path: "actions"  
model_generation_path: "models"
api_generation_path: "api"
tests_path: "tests"
service_path: "service"
apps_path: "apps" # For extending the service, growing the app with AI managed apps decoupled
logging_level: "ERROR"
reload: true
persist_cache_as_db: false
default_ai_model: "gpt-3.5-turbo"
fastapi_port: 5279
fastapi_host: "0.0.0.0"
assistant_id: "asst_01VdA1ESvylwvzqDoXGAO84N"
assistant_conversation_thread_id: ""
actions_cap: 128          # Set the cap for actions
actions_count: 0          # Updated dynamically to reflect the current count
warn_threshold: 100       # When to start warning about nearing the cap
expose_default_actions_to_ai: true
expose_project_actions_to_ai: true
expose_api_actions_to_ai: true
expose_default_actions_to_cli: true
expose_project_actions_to_cli: true

# Paths for different components
service_generation_path: "service"
data_path: "data"
logs_path: "logs"
docs_path: "docs"
path_path: "ui"
ui_clients_path: "clients"

# Directories to reload
reload_dirs:
  - "actions"
  - "models"
  - "service"
  - "api"
  - "data"
  - "tests"
