scripts_search_path: ""  # This sets the default search path to the current working directory
model_generation_path: ""
reload_dirs:
 - "./models"
 - "./endpoints"
 - "./script"
reload: true
persist_cache_as_db: false
logging:
  date_format: "%Y-%m-%d %H:%M:%S"
  log_colors:
    DEBUG: "cyan"
    INFO: "green"
    WARNING: "yellow"
    ERROR: "red"
    CRITICAL: "red,bg_white"
  secondary_log_colors:
    message:
      ERROR: "red"
      CRITICAL: "red"
      WARNING: "yellow"
      INFO: "green"
      DEBUG: "cyan"

assistant_ids:
  cli_assistant: ""
  codegen_assistant: ""

default_ai_model: "gpt-3.5-turbo"
fastapi_port: 5279
fastapi_host: "0.0.0.0"
do_not_discover: false
assistant_id: ""
assistant_conversation_thread_id: ""
